# Application Name (required for Config Server to know which config to fetch)
spring.application.name=api-gateway

# Config Server Location (fetches all other configuration from here)
spring.config.import=optional:configserver:http://localhost:8888
