spring:
  datasource:
    url: jdbc:postgresql://postgres-restaurant:5432/restaurantdb
    username: foodexpress
    password: foodexpress123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

feign:
  client:
    config:
      menu-service:
        connectTimeout: 5000
        readTimeout: 5000
