# RabbitMQ Configuration — FoodExpress
default_user = guest
default_pass = guest
default_vhost = /

# Management plugin
management.tcp.port = 15672

# Logging
log.console = true
log.console.level = info

# Memory
vm_memory_high_watermark.relative = 0.6
disk_free_limit.absolute = 500MB
